// <auto-generated />
using Microsoft.Phone.Controls;

namespace PhoneGap
{
    public partial class MainPage : PhoneApplicationPage
    {
        /*
         * Generates the list of files used
         * This is needed as all files must be loaded
         * to IsolatedStorage and run from there.
         */
        private static string[] AllFilesInWwwFolder()
        {
            return new[] {
                           "www/index.html",
                           "www/mobile-spec.html",
                           "www/pg_logo.png",
                           "www/css/master.css",
                           "www/css/qunit.css",
                           "www/images/ArrowImg.png",
                           "www/js/phonegap.js",
                           "www/js/qunit.js",
                           "www/js/tests/accelerometer.tests.js",
                           "www/js/tests/camera.tests.js",
                           "www/js/tests/contacts.tests.js",
                           "www/js/tests/device.tests.js",
                           "www/js/tests/file.tests.js",
                           "www/js/tests/geolocation.tests.js",
                           "www/js/tests/map.tests.js",
                           "www/js/tests/media.tests.js",
                           "www/js/tests/network.tests.js",
                           "www/js/tests/notification.tests.js",
                           "www/js/tests/orientation.tests.js",
                           "www/js/tests/sms.tests.js",
                           "www/js/tests/storage.tests.js",
                           "www/js/tests/telephony.tests.js",
                        };
        }
    }
}