// <auto-generated />
using Microsoft.Phone.Controls;

namespace PhoneGap
{
    public partial class MainPage : PhoneApplicationPage
    {
        /*
         * Generates the list of files used
         * This is needed as all files must be loaded
         * to IsolatedStorage and run from there.
         */
        private static string[] AllFilesInWwwFolder()
        {
            return new[] {
                           "www/index.html",
                           "www/master.css",
                           "www/pg_logo.png",
                           "www/phonegap.js",
                           "www/images/ArrowImg.png",
                        };
        }
    }
}